# Generated by Django 3.1.7 on 2022-10-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('tecnology', models.CharField(max_length=200, verbose_name='Tipo')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
        ),
    ]
